### ISSUE TITLE
What does "typelib not found" mean?

### ISSUE THREAD

**Issue by cookiengineer** [Place1/node-gir#48]
I wanted to try out the `examples/browser.js` demo in order to find out whether `node-gir` is a viable alternative for using `webkit2gtk` (or similar) libraries that are already installed on the system.

But I only get the message `Error: Typelib file for namespace 'WebKit', version '3.0' not found`.

What does this message mean, and _where_ does node-gir look for files or libraries?
How can I make this work? The GTK demo and others work fine.

OS: Arch Linux / x64, all up-to-date, and all libraries come with headers preinstalled by default.

**Comment by Place1** [comment]
Hey, this probably means some development libs are installed (the ones that contain the GObject typelib metadata). Unfortuantly I've kinda abandoned this project due to lack of time so that's about as much help as I can give. I'd recommend you don't base any software on this project.

maybe have a look at: https://github.com/romgrk/node-gtk
